### ISSUE TITLE
Unable to load custom panel from [REDACTED]:8123/hacsfiles/frontend-20200212060803.js

### ISSUE THREAD

**Issue by jjanderson** [hacs/frontend#78]
Version of HACS
LATEST

Describe the bug
When clicking on the HACS option in side panel, I get an error message:

Unable to load custom panel from [REDACTED]:8123/hacsfiles/frontend-20200212060803.js

Debug log
NO LOGS AVAILABLE

**Comment by jjanderson** [comment]
Further to this, I am now getting a complete component failure on restart

```
2020-02-14 12:56:49 ERROR (MainThread) [homeassistant.setup] Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/aiogithub.py", line 144, in get_ratelimit
    response = await self.session.get(url, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 967, in _create_direct_connection
    traces=traces), loop=self._loop)
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 170, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/hacs/__init__.py", line 41, in async_setup
    await startup_wrapper_for_yaml(Hacs)
  File "/config/custom_components/hacs/__init__.py", line 77, in startup_wrapper_for_yaml
    startup_result = await hacs_startup(hacs)
  File "/config/custom_components/hacs/__init__.py", line 131, in hacs_startup
    if not await load_hacs_repository(hacs):
  File "/config/custom_components/hacs/setup.py", line 17, in load_hacs_repository
    await hacs().register_repository("hacs/integration", "integration")
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 157, in register_repository
    await repository.registration()
  File "/config/custom_components/hacs/repositories/integration.py", line 83, in registration
    if not await self.validate_repository():
  File "/config/custom_components/hacs/repositories/integration.py", line 36, in validate_repository
    self.information.full_name
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/aiogithub.py", line 51, in get_repo
    await self.get_ratelimit()
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/aiogithub.py", line 159, in get_ratelimit
    self.ratelimits.core.reset = int(response.headers["X-RateLimit-Reset"])
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
2020-02-14 12:56:49 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform hacs.sensor: Unable to set up component.
```

**Comment by jjanderson** [comment]
I deleted the component and tried to add it again via the UI

I am now getting "unknown Issue"

![image](https://user-images.githubusercontent.com/1214287/74539125-6be12680-4f35-11ea-8538-e8b43efe58bd.png)

**Comment by ludeeus** [comment]
You have network issues, your HA instance gets timeouts contacting external services.
